baseURL = "https://ai.sytes.ru"
languageCode = "ru-RU"
title = "Archie"
theme="archie"
copyright = "© Tftlegal"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/tftlegal"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/tftlegal/?profileId=ACoAAFo9ZeUB0XmxaRme7cAvDTWOxtJYWjg-us8/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.sytes.ru/tftlegal/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Search"
url = "/search/"
weight = 5

[markup.goldmark.renderer]
unsafe = true
